name: Java CI com Maven

on:
  push:
    branches: [ atividade-rafael-vieira ]
  pull_request:
    branches: [ atividade-rafael-vieira ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar e Testar com Maven
        run: ./mvnw clean verify
